name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,main,release ]
  pull_request:
    branches: [ master,main,release ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry mypy types-termcolor

    - name: Run mypy checks
      run: mypy --strict --ignore-missing-imports --show-error-codes --exclude docs/ --exclude tests/ .
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -E test

      - name: Run pytest checks
        run:
          poetry run pytest

  # publish_dev_build:
  #   # if test failed, we should not publish
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install poetry tox tox-gh-actions

  #     - name: test with tox
  #       run:
  #         tox

  #     - name: list files
  #       run: ls -l .

  #     - uses: codecov/codecov-action@v1
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: true
  #         files: coverage.xml

  #     - name: Build wheels and source tarball
  #       run: |
  #         poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
  #         poetry version --short
  #         poetry build

  #     - name: publish to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         user: __token__
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN}}
  #         repository_url: https://test.pypi.org/legacy/
  #         skip_existing: true